# Generated by Django 3.0.7 on 2020-07-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_stops', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('line_id', 'direction', 'program_number', 'planned_arrival', 'stop_id')},
        ),
    ]
