# Generated by Django 3.0.7 on 2020-07-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20200721_1058'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['stop_id', 'line_id', 'direction', 'program_number', 'planned_arrival'], name='timetable_stop_id_dbe3a8_idx'),
        ),
    ]
