# Generated by Django 3.0.7 on 2020-07-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_stops', '0002_auto_20200727_1708'),
        ('timetable', '0002_auto_20200729_1145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('line_id', 'direction', 'program_number', 'planned_arrival', 'stop_id')},
        ),
    ]
