# Generated by Django 3.0.7 on 2020-07-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinesPrognumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=10)),
                ('direction', models.IntegerField()),
                ('first_program_number', models.IntegerField()),
                ('last_program_number', models.IntegerField()),
            ],
            options={
                'db_table': 'lines_prognumbers',
                'managed': True,
                'unique_together': {('line', 'direction')},
            },
        ),
    ]
