# Generated by Django 3.0.7 on 2020-07-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_prognumber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linesprognumbers',
            old_name='line',
            new_name='line_id',
        ),
        migrations.AlterUniqueTogether(
            name='linesprognumbers',
            unique_together={('line_id', 'direction')},
        ),
    ]
