# Generated by Django 3.0.7 on 2020-07-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_prognumber', '0002_auto_20200701_2210'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='linesprognumbers',
            index=models.Index(fields=['line_id', 'direction', 'first_program_number', 'last_program_number'], name='lines_progn_line_id_77aed8_idx'),
        ),
    ]
