# Generated by Django 3.0.7 on 2020-07-23 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus_stops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopsRoutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=10)),
                ('program_number', models.IntegerField()),
                ('direction', models.IntegerField()),
                ('stop_id', models.ForeignKey(db_column='stop_id', on_delete=django.db.models.deletion.PROTECT, to='bus_stops.BusStops')),
            ],
            options={
                'db_table': 'stops_routes',
                'managed': True,
                'unique_together': {('route', 'stop_id', 'direction')},
            },
        ),
    ]
