# Generated by Django 3.0.7 on 2020-06-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops_routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopsroutes',
            name='route',
            field=models.CharField(max_length=10),
        ),
    ]
