# Generated by Django 3.0.7 on 2020-07-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_stops', '0001_initial'),
        ('stops_routes', '0002_auto_20200701_0725'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stopsroutes',
            unique_together={('route', 'stop_id')},
        ),
    ]
