# Generated by Django 3.0.7 on 2020-06-30 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_stops', '0001_initial'),
        ('stops_routes', '0003_auto_20200630_1409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stopsroutes',
            unique_together={('stop_id', 'route'), ('route', 'program_number')},
        ),
    ]
