# Generated by Django 3.0.7 on 2020-07-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_stops', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='busstops',
            index=models.Index(fields=['stop_id', 'stop_name', 'stop_lat', 'stop_lng'], name='bus_stops_stop_id_01fb71_idx'),
        ),
    ]
