# Generated by Django 3.0.7 on 2020-07-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinesRouteID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.IntegerField()),
                ('line_id', models.CharField(max_length=10)),
                ('route_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'lines_routeids',
                'managed': True,
                'unique_together': {('line_id', 'direction')},
            },
        ),
    ]
