# Generated by Django 3.0.7 on 2020-07-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_routeid', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='linesrouteid',
            index=models.Index(fields=['direction', 'line_id', 'route_id'], name='lines_route_directi_9bc012_idx'),
        ),
    ]
