# Generated by Django 3.0.7 on 2020-07-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='weather',
            name='weather_date_en_cb0dff_idx',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='date_entry',
            new_name='date_weather',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='hour_Day',
            new_name='hour_of_Day',
        ),
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together={('date_weather', 'hour_of_Day')},
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['date_weather', 'hour_of_Day', 'feels_like', 'wind_speed', 'weather_id', 'temp', 'temp_min', 'temp_max', 'humidity', 'weather_main', 'weather_description'], name='weather_date_we_2da8c3_idx'),
        ),
    ]
